### ISSUE TITLE
xmllint error not in reject error output

### ISSUE THREAD

**Issue by pyason** [aautio/validate-with-xmllint#1]
Hi, it would be nice if you could include stderr piped in stderr output of xmllint to promise reject error object.

Currently if a validation failed I could only see the statement of "validation failed...." without detail on where the failure occurs, which is displayed in console output. It'd be nice if I could take that output an log in error in my code as well.

Thanks,
Paul

**Comment by aautio** [comment]
@pyason great idea! I'll check if I could suppress all unnecessary stdout output on successful validations and reject with stderr as you've suggested.

**Comment by aautio** [comment]
Hi @pyason - I've just published version `1.1.0` with the error output included in the promise rejection error.

https://www.npmjs.com/package/validate-with-xmllint

**Comment by pyason** [comment]
Thank you very much @aautio ! This is very quick haha. Have a nice one :)
