### ISSUE TITLE
 Failed at the validate-with-xmllint@1.2.0 postinstall script

### ISSUE THREAD

**Issue by Leigh-M** [aautio/validate-with-xmllint#12]
I am seeing this error (log below) but unclear what the postinstall script is checking for?

```
102 verbose stack Error: validate-with-xmllint@1.2.0 postinstall: `node ./lib/validate-xmllint-installation.js`
102 verbose stack Exit status 1
102 verbose stack     at EventEmitter.<anonymous> (/home/leigh/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
102 verbose stack     at EventEmitter.emit (events.js:315:20)
102 verbose stack     at ChildProcess.<anonymous> (/home/leigh/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
102 verbose stack     at ChildProcess.emit (events.js:315:20)
102 verbose stack     at maybeClose (internal/child_process.js:1048:16)
102 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
103 verbose pkgid validate-with-xmllint@1.2.0
104 verbose cwd /home/leigh/projects/test-stuff
105 verbose Linux 5.13.1-051301-generic
106 verbose argv "/home/leigh/.nvm/versions/node/v14.15.0/bin/node" "/home/leigh/.nvm/versions/node/v14.15.0/bin/npm" "i" "validate-with-xmllint"
107 verbose node v14.15.0
108 verbose npm  v6.14.8
109 error code ELIFECYCLE
110 error errno 1
111 error validate-with-xmllint@1.2.0 postinstall: `node ./lib/validate-xmllint-installation.js`
111 error Exit status 1
112 error Failed at the validate-with-xmllint@1.2.0 postinstall script.
112 error This is probably not a problem with npm. There is likely additional logging output above.
113 verbose exit [ 1, true ]
```

Any way to get further info on debugging this issue, there're no indicators why validation has failed? Thanks!

**Comment by fbeauchamp** [comment]
found it : you need to install `xmllint` on your system 
On ubuntu you need to do `sudo apt  install libxml2-utils`

**Comment by Leigh-M** [comment]
Thanks @fbeauchamp - is there any way to achieve the same just via node modules? (as sometimes you don't have access to the underlying OS - for local dev that's fine - but for production systems sometimes not - eg if the environment is an AWS lambda runtime (nodeJs 14) - cannot modify the OS - as far as I'm aware. Maybe build a custom lambda runtime, but seems overkill to validate an XML against and XSD - although there aren't currently any apps that are supposed do this and work, that I can find bizarrely)

**Comment by Leigh-M** [comment]
Failing locally now after `sudo apt install libxml2-utils`  with: Error: write EPIPE   at: `/home/leigh/projects/test-stuff/node_modules/validate-with-xmllint/lib/index.js:26:19`

**Comment by aautio** [comment]
The **FAQ** section at `README.md` provides some instructions for how to install `xmllint`. I've elaborated the FAQ section a bit in pull request #14.

Unfortunately I do not yet know how to provide `xmllint` for Lambda runtimes. If you find an easy way please let me know and I'll update the `README.md`.
